version: 2.1

jobs:
  build-bundle:
    docker:
      - image: misterabdul/android-build-environment:0.0.1-alpine
    steps:
      - checkout
      - run: |
          ./gradlew init
          ./gradlew :app:bundleRelease
          cp -r $(pwd)/app/build/outputs/bundle/* /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-bundle:
    jobs:
      - build-bundle
